version: 2
jobs:
  release:
    docker:
      - image: circleci/node:6

    working_directory: ~/oss

    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master
            tags:
              only: /v[0-9]+(.[0-9]+){2}/
